- name: Setup TODO APP
  hosts: all
  become_user: yes 

  tasks: 
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

- name: Start Nginx
    systemd:
      state: started
      name: nginx
      enabled: yes

- name: Download the component 
    get_url: 
      url: http://172.31.12.138:8081/repository/frontend/
      dest: var/www/html
      username: admin
      password: admin


- 