- name: Setup TODO APP
  hosts: all
  become_user: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enabled: yes

    - name: Download COMPONENT from Nexus
      get_url:
        url: http://172.31.12.138:8081/repository/frontend/frontend-main.zip
        dest: /var/www/html/frontend.zip
        username: admin
        password: admin

    - name: Unzip the Downloaded Content
      unarchive:
        src: /var/www/html/frontend.zip
        dest: /var/www/html
        remote_src: yes

    - name: Remove default files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default

    - name: Copy config file
      copy:
         src: /var/www/html/frontend.conf
         dest: /etc/nginx/sites-enabled/frontend.conf

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enabled: yes