- name: install npm
  include_role:
    name: common
    tasks_from: nodejs

- name: Download artifacts
  include_role:
    name: common
    tasks_from: download-nexus-artifacts

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/todo
    dest: /root/
    remote_src: yes

- name: Copy todo.Service
  templete:
    src: todo.service
    dest: /etc/systemd/system/todo.service

- name: Start todo Service
  systemd:
    name: todo
    daemon_reload: yes
    state: started
    enabled: yes