- name: install npm
  include_role:
    name: common
    tasks_from: nodejs

- name: Download artifacts
  include_role:
    name: common
    tasks_from: download-nexus-artifacts

- name: Copy todo.Service
  template:
    src: todo.service
    dest: /etc/systemd/system/todo.service

- name: Start todo Service
  systemd:
    name: todo
    daemon_reload: yes
    state: started
    enabled: yes

- name: Import nexus common role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Install Filebeat from common role
  include_role:
    name: common
    tasks_from: filebeat

  vars:
    IS_STRUCTURED: true
    LOG_FILES:
      - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" }