- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Download COMPONENT 
  include_role: 
    name: common
    tasks_from: download-nexus-artifacts


- name: Remove default files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html

- name: Create Frontend directory
  file:
    path: /var/www/html/frontend
    state: directory

- name: Unzip the Downloaded Content
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html/frontend
    remote_src: yes

- name: Update Todoshop Config file
  template:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf

- name: Start Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes


- name: Import nexus common role
  include_role:
    name: common
    tasks_from: node_exporter


- name: Install Filebeat from common role
  include_role:
    name: common
    tasks_from: filebeat

  vars:
    IS_STRUCTURED: false
    LOG_FILES:
      - { file: "/var/log/nginx/access.log", type: "nginx_access" }
      - { file: "/var/log/nginx/error.log", type: "nginx_error" }