- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Download COMPONENT from Nexus
  get_url:
    url: http://172.31.12.138:8081/repository/frontend/frontend-main.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin

- name: Create Frontend directory
  file:
    path: /var/www/html/frontend
    state: directory

- name: Unzip the Downloaded Content
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html/frontend
    remote_src: yes

- name: Remove default files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

- name: Update Todoshop Config file
  copy:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf

- name: Start Nginx
  command: cd /var/www/html/frontend ; npm start 

# - name: Start Nginx
#   systemd:
#     name: nginx
#     state: restarted
#     enabled: yes