- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Download COMPONENT 
  include_role: 
    name: common
    tasks_from: download-nexus-artifacts.yml
    

- name: Remove default files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html

- name: Create Frontend directory
  file:
    path: /var/www/html/frontend
    state: directory

- name: Unzip the Downloaded Content
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html/frontend
    remote_src: yes

- name: Update Todoshop Config file
  template:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf

- name: Start Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes