- name: Install Java
  include_role:
    name: common
    tasks_from: java

- name: Download artifacts
  include_role:
    name: common
    tasks_from: download-nexus-artifacts

- name: Unzip the Downloaded Content
  unarchive:
    src: /tmp/users.zip
    dest: /root/
    remote_src: yes

- name: Copy Systemd
  template:
    src: users.service
    dest: /etc/systemd/system/users.service

- name: Start Users Service
  systemd:
    name: users
    daemon_reload: yes
    state: started
    enabled: yes

- name: Import nexus common role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Install Filebeat from common role
  include_role:
    name: common
    tasks_from: filebeat