- name: golang common role
  include_role:
    name: common
    tasks_from: golang 

- name: Download artifacts
  include_role:
    name: common
    tasks_from: download-nexus-artifacts

- name: Copy login.Service
  template:
    src: login.service
    dest: /etc/systemd/system/login.service

- name: Start login Service
  systemd:
    name: login
    daemon_reload: yes
    state: started
    enabled: yes