- name: Install Go
  apt:
    name: golang
    update_cache: yes
    state: present

- name: Download COMPONENT from Nexus
  get_url:
    url: http://172.31.12.138:8081/repository/login/login-main.zip
    dest: /root/login
    username: admin
    password: admin

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/login
    dest: /root/
    remote_src: yes

- name: Copy login.Service
  copy:
    src: login.service
    dest: /etc/systemd/system/login.service

- name: Start login Service
  systemd:
    name: login
    daemon_reload: yes
    state: started
    enabled: yes