- name: Update todo service file
  template:
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state: started
    enabled: yes